# Generated by Django 3.2.7 on 2021-10-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groupmsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('messege', models.TextField(null=True)),
                ('messege_sent_at', models.DateTimeField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'ordering': ['messege_sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NickNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('nickname', models.CharField(max_length=50)),
            ],
        ),
    ]
